apiVersion: v1
kind: Service
metadata:
  namespace: ml-project
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # ✅ le service écoute sur 80
      targetPort: 80    # ✅ ton conteneur écoute sur 80
      nodePort: 30001   # ✅ accessible depuis http://localhost:30001
      name: frontend-http

